---
title: "team.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) 
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyr)
#library(plotly)
library(ggrepel)
```

```{r} 

acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)

per <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)

```

### 1
```{r}

acc$DAY_WEEK <- wday(acc$DAY_WEEK, label = TRUE)

accidents <- acc %>%
              group_by(DAY_WEEK) %>%
              summarise(count = n())

```

```{r}

ggplot(data = accidents, aes(x = DAY_WEEK, y = count)) + geom_bar(stat = 'identity')

```


### 2
```{r}

fatal <- filter(per, INJ_SEV == 4)
head(fatal)

```

### 3
```{r}

temp <- fatal %>%
          group_by(STATE, MAKE) %>%
          summarize(n = n())

head(temp)

```

```{r}

mostDangerous <- temp %>%
                  na.omit() %>%
                  group_by(STATE) %>%
                  filter(n == max(n))
head(mostDangerous)

```



### 4
```{r}

glc <- readxl::read_xlsx('GLC.xlsx')

glc$'State Code' <- as.numeric(glc$'State Code')

glc

```

```{r}

data <- left_join(mostDangerous, glc, by = c("STATE" = "State Code")) %>%
  select(STATE, MAKE, n, 'State Name') %>%
  distinct()

```

```{r} 

state <- map_data("state")

stateMap <- state %>%
  group_by(region) %>%
  summarize(long = mean(long), lat = mean(lat))

stateMap$region <- toupper(stateMap$region)

stateMapData <- data %>%
  left_join(stateMap, by = c("State Name" = "region")) %>%
  select(STATE, MAKE, n, 'State Name', long, lat) %>%
  distinct()

#ggplot(state, aes(x='long',y='lat')) + geom_polygon(aes(group=group)) + geom_text(data = stateMap, aes(label=MAKE))

```


```{r}
#sMap <- state %>%
  #ggplot(aes(x = long, y = lat)) + geom_polygon(aes(group = group), color = 'white') + coord_map() + geom_label_repel(data = stateMapData, aes(label = MAKE), size = 2, max.overlaps = Inf)

ggplot(data = state, aes(x = long, y = lat)) + geom_polygon(aes(group = group), color = 'white') + geom_label_repel(data = stateMapData, aes(label = MAKE), size = 2, max.overlaps = Inf)
```

### 5
```{r}
accidents <- inner_join(acc, per, by=c('STATE', 'ST_CASE', 'VE_FORMS', 'COUNTY', 'DAY', 'MONTH', 'HOUR', 'MINUTE', 'RUR_URB', 'FUNC_SYS', 'HARM_EV', 'MAN_COLL', 'SCH_BUS'))
head(accidents)
```

### 6
```{r}
#accidents %>% filter(INJ_SEV == 4) %>% table(DAY_WEEK)
#ggplot(fatal, aes(x= ,y=)) + geom_boxplot()
table(fatal$HOUR)
fatal %>% slice(1:24) %>% ggplot(aes(x=HOUR)) + geom_bar()
table(fatal$SEX)
fatal %>% filter(SEX==c(1,2))  %>% ggplot(aes(x=SEX)) + geom_bar()
```

### 7
```{r}
accidents %>% filter(INJ_SEV==4) %>% ggplot() + geom_polygon(aes(fill=INJ_SEV ,x=LONGITUDE, y=LATITUDE, group=COUNTY))
```

### 8
```{r}
winter <- accidents %>% filter(MONTH==c(12,1,2))
summer <- accidents %>% filter(MONTH==c(6,7,8))
winter %>% table(INJ_SEV)
summer %>% table(INJ_SEV)
```